services:
  redis:
    image: redis
    expose:
      - 6379
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 3

  rabbitmq:
    image: rabbitmq
    expose:
      - 5672
    healthcheck:
      test: rabbitmq-diagnostics check_port_connectivity
      start_period: 10s
      interval: 30s
      timeout: 10s
      retries: 3

  cabs-event-generator: 
    build:
      context: .
      dockerfile: Dockerfile 
    environment:
     RABBITMQ_CONN_STRING: "amqp://guest:guest@rabbitmq" 
    depends_on:
      rabbitmq:
        condition: service_healthy
    entrypoint: ["./event-generator-sim"]

  cabs-location-updator:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
     RABBITMQ_CONN_STRING: "amqp://guest:guest@rabbitmq" 
     REDIS_CONN_STRING: "redis://:@redis:6379/0"
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    entrypoint: ["./location-updator-sim"]

  cabs-processor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    environment:
     RABBITMQ_CONN_STRING: "amqp://guest:guest@rabbitmq" 
     REDIS_CONN_STRING: "redis://:@redis:6379/0"
    depends_on:
      rabbitmq:
        condition: service_healthy
      redis:
        condition: service_healthy
    entrypoint: ["./processor"]
